### ISSUE TITLE
tests not working for 0.21.7 on ruby 3.1

### ISSUE THREAD

**Issue by Segaja** [ruby/typeprof#145]
Hi,

I'm trying to build typeprof 0.21.7 against ruby 3.1 but I'm getting errors from the tests:

```
(none):1: warning: possibly useless use of a literal in void context
Loaded suite /usr/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader
Started
....F
===============================================================================
Failure: test: testbed/diff-lcs(TypeProf::DiffLCSTest): <nil> is not true.
/build/ruby-typeprof/src/typeprof-0.21.7/test/typeprof/diff-lcs_test.rb:20:in `block in <class:DiffLCSTest>'
     17:
     18:         # No special reason to choose these two classes (Goodcheck::Analyzer and Trigger)
     19:
  => 20:         assert(actual =~ /^module Diff\n  module LCS\n(?:(?:    .*?\n|\n)*)^  end\n^end\n/)
     21:         assert_include($&, "def self.diff: (Array[T] | LCS seq1, Array[T] seq2, ?nil callbacks) ?{ (Array[Change] | Change | ContextChange) -> nil } -> (Array[(Array[Change?] | Change | ContextChange)?])")
     22:
     23:         assert(actual =~ /^    class Change\n(?:(?:      .*?\n|\n)*)^    end\n/)
===============================================================================
E
===============================================================================
Error: test: testbed/goodcheck(TypeProf::GoodcheckTest): Bundler::GemfileNotFound: /build/ruby-typeprof/src/typeprof-0.21.7/testbed/goodcheck/Gemfile not found
/usr/lib/ruby/3.1.0/bundler/definition.rb:36:in `build'
/usr/lib/ruby/3.1.0/bundler.rb:207:in `definition'
/usr/lib/ruby/3.1.0/bundler.rb:155:in `setup'
/build/ruby-typeprof/src/typeprof-0.21.7/test/typeprof/goodcheck_test.rb:34:in `block in <class:GoodcheckTest>'
===============================================================================(none):25: warning: possibly useless use of a constant in void context
path/to/file:25: warning: possibly useless use of a constant in void context

....TypeProf for IDE is started successfully
...........................................................................
...............................................................................
...............................................................................
............................................................................
Finished in 48.261118663 seconds.
-------------------------------------------------------------------------------
319 tests, 355 assertions, 1 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
99.373% passed
-------------------------------------------------------------------------------
6.61 tests/s, 7.36 assertions/s
rake aborted!
```

Any idea what is wrong?

**Comment by Segaja** [comment]
I realized this would work having `git` installed. The fact the the dependency checkout silently fails without `git` available could be improved.
