### ISSUE TITLE
`make test-bundled-gems` failed with mswin environment(not mingw)

### ISSUE THREAD

**Issue by hsbt** [ruby/typeprof#276]
I got test failure of typeprof performed by `make test-bundled-gems` at `ruby/ruby` repository with my Windows environment:

```
F
====================================================================================================================================================================================
Failure: test_diagnostics(TypeProf::LSP::LSPTest)
C:/Users/hsbt/DevDrive/github.com/ruby/ruby/gems/src/typeprof/test/lsp/lsp_test.rb:189:in 'block in TypeProf::LSP::LSPTest#test_diagnostics'
C:/Users/hsbt/DevDrive/github.com/ruby/ruby/gems/src/typeprof/test/lsp/lsp_test.rb:90:in 'TypeProf::LSP::LSPTest#expect_notification'
C:/Users/hsbt/DevDrive/github.com/ruby/ruby/gems/src/typeprof/test/lsp/lsp_test.rb:188:in 'TypeProf::LSP::LSPTest#test_diagnostics'
<[{:message=>"wrong number of arguments (2 for 1)",
  :range=>{:end=>{:character=>3, :line=>4}, :start=>{:character=>0, :line=>4}},
  :severity=>1,
  :source=>"TypeProf"}]> expected but was
<[{:message=>"wrong number of arguments (2 for 1)",
  :range=>{:end=>{:character=>3, :line=>4}, :start=>{:character=>0, :line=>4}},
  :severity=>1,
  :source=>"TypeProf"},
 {:message=>"wrong number of arguments (2 for 1)",
  :range=>{:end=>{:character=>3, :line=>4}, :start=>{:character=>0, :line=>4}},
  :severity=>1,
  :source=>"TypeProf"}]>

diff:
  [{:message=>"wrong number of arguments (2 for 1)",
    :range=>{:end=>{:character=>3, :line=>4}, :start=>{:character=>0, :line=>4}},
    :severity=>1,
+   :source=>"TypeProf"},
+  {:message=>"wrong number of arguments (2 for 1)",
+   :range=>{:end=>{:character=>3, :line=>4}, :start=>{:character=>0, :line=>4}},
+   :severity=>1,
    :source=>"TypeProf"}]
====================================================================================================================================================================================
```

and

```
F
====================================================================================================================================================================================
Failure: test_hover(TypeProf::LSP::LSPTest)
C:/Users/hsbt/DevDrive/github.com/ruby/ruby/gems/src/typeprof/test/lsp/lsp_test.rb:144:in 'block in TypeProf::LSP::LSPTest#test_hover'
C:/Users/hsbt/DevDrive/github.com/ruby/ruby/gems/src/typeprof/test/lsp/lsp_test.rb:82:in 'TypeProf::LSP::LSPTest#expect_response'
C:/Users/hsbt/DevDrive/github.com/ruby/ruby/gems/src/typeprof/test/lsp/lsp_test.rb:143:in 'TypeProf::LSP::LSPTest#test_hover'
<{:contents=>{:language=>"ruby", :value=>"Integer"}}> expected but was
<{:contents=>{:language=>"ruby", :value=>"(Integer | String)"}}>

diff:
? {:contents=>{:language=>"ruby", :value=>"(Integer | String)"}}
====================================================================================================================================================================================
```

Please let me know if you want additional details.

**Comment by mame** [comment]
I guess this is fixed by https://github.com/ruby/typeprof/pull/278
