### ISSUE TITLE
URI require issue

### ISSUE THREAD

**Issue by wagenet** [ruby/typeprof#79]
A file with the following causes a crash

```rb
require 'uri/generic'
require 'uri'
```

```
/Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/analyzer.rb:1252:in `block (2 levels) in get_instance_variable': undefined method `detailed_source_location' for nil:NilClass (NoMethodError)
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/analyzer.rb:1245:in `each'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/analyzer.rb:1245:in `block in get_instance_variable'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/analyzer.rb:851:in `block in add_write!'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/analyzer.rb:850:in `each'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/analyzer.rb:850:in `add_write!'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/analyzer.rb:896:in `block in add_ivar_write!'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/type.rb:90:in `each_child'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/analyzer.rb:892:in `add_ivar_write!'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/import.rb:611:in `block (2 levels) in import'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/import.rb:606:in `each'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/import.rb:606:in `block in import'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/import.rb:577:in `each'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/import.rb:577:in `import'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/import.rb:529:in `import_library'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/builtin.rb:643:in `file_require'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/builtin.rb:684:in `kernel_require'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/method.rb:323:in `[]'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/method.rb:323:in `do_send'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/analyzer.rb:2392:in `block (2 levels) in do_send'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/utils.rb:101:in `each_key'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/utils.rb:101:in `each'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/analyzer.rb:2391:in `block in do_send'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/type.rb:90:in `each_child'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/analyzer.rb:2367:in `do_send'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/analyzer.rb:1512:in `step'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/analyzer.rb:1050:in `type_profile'
        from /Users/peterwagenet/Development/Ruby/typeprof/lib/typeprof/config.rb:123:in `analyze'
        from exe/typeprof:9:in `<main>'
```

**Comment by wagenet** [comment]
It looks like the issue is this line being called when `ep` is `nil`: https://github.com/ruby/typeprof/blob/21f1ba28d78eb26576b73fa22aaa5a3970f2a418/lib/typeprof/analyzer.rb#L851
